#!/usr/bin/env python3
"""One-time migration: move settings that are IDENTICAL across every bot's .env into a shared
common.env (loaded before each bot's .env), and remove them from the per-bot files. Keys that
differ between bots, or that only some bots have, stay per-bot. No guessing — a key is moved
only when every bot already has the exact same value. Backs up every file it touches (.bak),
so it's reversible. Safe to re-run.

Run with the bot's Python:  ~/telegram-bot/venv/bin/python migrate_common_env.py
"""
import re
import sys
from pathlib import Path

HOME = Path.home()
BOT_SRC = HOME / "telegram-bot"
CANDIDATE_BOTS = ["nora", "bonnie", "cass", "emily", "jules", "priya"]
# Never centralize these, even if they happen to match — they're identity/secret per instance.
NEVER_SHARE = {"TELEGRAM_BOT_TOKEN", "BOT_TOKEN", "CHARACTER_CARD", "NAME", "BOT_HOME"}
KEY_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$")


def parse(p: Path) -> dict:
    d = {}
    for line in p.read_text(encoding="utf-8").splitlines():
        if line.lstrip().startswith("#"):
            continue
        m = KEY_RE.match(line)
        if m:
            d[m.group(1)] = m.group(2)
    return d


def backup(p: Path):
    p.with_suffix(p.suffix + ".bak").write_text(p.read_text(encoding="utf-8"), encoding="utf-8")


def redact(k: str, v: str) -> str:
    return "***" if any(s in k.upper() for s in ("KEY", "TOKEN", "PASSWORD", "SECRET")) else v


def main():
    bots = [(b, HOME / f"{b}-bot" / ".env") for b in CANDIDATE_BOTS
            if (HOME / f"{b}-bot" / ".env").exists()]
    if len(bots) < 2:
        print(f"Need at least 2 bot .env files to compare; found {len(bots)}.")
        return 1
    print("Comparing:", ", ".join(b for b, _ in bots))

    parsed = {b: parse(p) for b, p in bots}
    all_keys = set().union(*(set(d) for d in parsed.values()))
    shared = {}
    for k in sorted(all_keys):
        if k in NEVER_SHARE:
            continue
        vals = [parsed[b].get(k) for b, _ in bots]
        if all(v is not None for v in vals) and len(set(vals)) == 1:
            shared[k] = vals[0]

    if not shared:
        print("No settings are identical across all bots — nothing to centralize.")
        return 0

    common_path = BOT_SRC / "common.env"
    # Merge with any existing common.env so a prior partial migration isn't lost.
    common_kv = parse(common_path) if common_path.exists() else {}
    common_kv.update(shared)

    if common_path.exists():
        backup(common_path)
    for _, p in bots:
        backup(p)

    lines = ["# Shared settings — loaded before each bot's .env, which overrides these.",
             "# Generated by migrate_common_env.py; edit shared values here once for all bots."]
    lines += [f"{k}={common_kv[k]}" for k in sorted(common_kv)]
    common_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    for _, p in bots:
        kept = []
        for line in p.read_text(encoding="utf-8").splitlines():
            m = KEY_RE.match(line)
            if m and not line.lstrip().startswith("#") and m.group(1) in shared:
                continue
            kept.append(line)
        p.write_text("\n".join(kept) + "\n", encoding="utf-8")

    print(f"\nCentralized {len(shared)} setting(s) into {common_path}:")
    for k in sorted(shared):
        print(f"  {k}={redact(k, shared[k])}")
    print(f"\nRemoved them from {len(bots)} per-bot .env file(s). Backups saved as .env.bak.")
    print("Now restart:  bash ~/telegram-bot/update-all.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
