#!/usr/bin/env bash
# Installs the bot fleet on a VPS (Ubuntu 24.04 recommended), supervised by systemd
# instead of the Termux tmux+run-bot.sh+watchdog.sh stack.
#
# Usage: sudo bash install-vps.sh
#
# Safe to re-run: skips steps that are already done (existing clone gets `git pull`
# instead of a fresh clone, existing .env files are left alone, only instances whose
# config actually changed get restarted).
set -euo pipefail

REPO_URL="https://github.com/biggieb327-lgtm/SillyTavernPresets.git"
INSTALL_DIR="/opt/telegram-bots"
BOT_USER="bot"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this with sudo: sudo bash install-vps.sh" >&2
  exit 1
fi

echo "== 1/8: system packages =="
if ! command -v git >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
  apt-get update -qq
  apt-get install -y git python3 python3-venv python3-pip
fi

echo "== 2/8: cloning / updating repo =="
if [ -d "$INSTALL_DIR/.git" ]; then
  git -C "$INSTALL_DIR" pull --ff-only
else
  mkdir -p "$INSTALL_DIR"
  git clone "$REPO_URL" "$INSTALL_DIR/repo"
  # The repo's telegram-companion-bot/ subfolder is what actually gets deployed;
  # keep INSTALL_DIR itself as the flat bot.py/venv/instances layout.
  shopt -s dotglob
  cp -r "$INSTALL_DIR"/repo/telegram-companion-bot/* "$INSTALL_DIR"/
  rm -rf "$INSTALL_DIR"/repo
  shopt -u dotglob
fi

echo "== 3/8: python venv =="
if [ ! -x "$INSTALL_DIR/venv/bin/python" ]; then
  python3 -m venv "$INSTALL_DIR/venv"
fi
# Single source of truth for pip installs — never hand-list packages here (a past
# hand-typed list silently dropped tzdata and broke every timezone-dependent feature).
"$INSTALL_DIR/venv/bin/pip" install -q --upgrade pip
"$INSTALL_DIR/venv/bin/pip" install -q -r "$INSTALL_DIR/requirements.txt"

echo "== 4/8: bot system user =="
if ! id -u "$BOT_USER" >/dev/null 2>&1; then
  useradd --system --home-dir "$INSTALL_DIR" --shell /usr/sbin/nologin "$BOT_USER"
fi
chown -R "$BOT_USER:$BOT_USER" "$INSTALL_DIR"

echo "== 5/8: configure instances =="
echo "Enter each instance you want to run. Leave the name blank to stop adding instances."
CONFIGURED_INSTANCES=()
while true; do
  read -rp "Instance name (e.g. nora, bonnie) [blank to finish]: " INSTANCE_NAME
  [ -z "$INSTANCE_NAME" ] && break
  INSTANCE_DIR="$INSTALL_DIR/$INSTANCE_NAME"
  ENV_FILE="$INSTANCE_DIR/.env"
  mkdir -p "$INSTANCE_DIR"

  if [ -f "$ENV_FILE" ]; then
    echo "  $ENV_FILE already exists — leaving it as-is. Edit it by hand and re-run to restart the unit."
  else
    read -rp "  Telegram bot token: " TG_TOKEN
    read -rp "  NanoGPT API key: " NANOGPT_KEY
    read -rp "  Character card filename (e.g. ${INSTANCE_NAME}.json): " CARD_NAME
    CARD_NAME="${CARD_NAME:-$INSTANCE_NAME.json}"
    ADMIN_TOKEN="$(openssl rand -hex 24 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9')"

    cp "$INSTALL_DIR/.env.example" "$ENV_FILE"
    {
      echo ""
      echo "# --- Generated by install-vps.sh ---"
      echo "TELEGRAM_BOT_TOKEN=$TG_TOKEN"
      echo "NANOGPT_API_KEY=$NANOGPT_KEY"
      echo "CHARACTER_CARD=$CARD_NAME"
      echo "ADMIN_API_ENABLED=1"
      echo "ADMIN_API_TOKEN=$ADMIN_TOKEN"
      echo "ADMIN_API_BIND=127.0.0.1"
    } >> "$ENV_FILE"
    echo "  Wrote $ENV_FILE (admin API token generated — bind it to your Tailscale IP"
    echo "  by setting ADMIN_API_BIND once Tailscale is set up, see step 7 below)."
  fi

  CARD="$(grep -m1 '^CHARACTER_CARD=' "$ENV_FILE" | cut -d= -f2)"
  if [ -n "$CARD" ] && [ -f "$INSTALL_DIR/$CARD" ] && [ ! -f "$INSTANCE_DIR/$CARD" ]; then
    cp "$INSTALL_DIR/$CARD" "$INSTANCE_DIR/$CARD"
  fi
  chown -R "$BOT_USER:$BOT_USER" "$INSTANCE_DIR"
  CONFIGURED_INSTANCES+=("$INSTANCE_NAME")
done

echo "== 6/8: systemd unit =="
cp "$INSTALL_DIR/deploy/bot@.service" /etc/systemd/system/bot@.service
systemctl daemon-reload

echo "== 7/8: enabling instances =="
for name in "${CONFIGURED_INSTANCES[@]}"; do
  systemctl enable --now "bot@${name}"
  echo "  bot@${name} enabled. Logs: journalctl -u bot@${name} -f"
done

echo "== 8/8: Tailscale =="
if ! command -v tailscale >/dev/null 2>&1; then
  cat <<'EOF'
Tailscale is not installed. It's a one-time, interactive step this script won't
automate (it needs its own device auth flow):

  curl -fsSL https://tailscale.com/install.sh | sh
  tailscale up

Once connected, find this host's tailnet IP with `tailscale ip -4`, then set
ADMIN_API_BIND=<that IP> in each instance's .env and restart it (systemctl restart
bot@<name>) so the admin API is actually reachable over the tailnet. It's left at
127.0.0.1 (loopback-only, unreachable) until you do this.
EOF
else
  echo "Tailscale already installed. Tailnet IP: $(tailscale ip -4 2>/dev/null || echo 'not connected — run: tailscale up')"
fi

echo ""
echo "Done. Configured instances: ${CONFIGURED_INSTANCES[*]:-(none)}"
